name: mnist_cls
model:
  _target_: problem.mnist.MNIST_classifier
  sigma_noise: 0.01

data:
  _target_: data.mnist.MNIST
  train: False
  discrete: True
  num_samples: 1000

evaluator:
  _target_: eval.MNIST_evaluator_cls

visualizer:
  _target_: visualize.MNIST_visualizer

exp_dir: exps/mnist_cls
