name: mnist_xor
model:
  _target_: problem.basic.XOR
  ratio: 0.5
  length: 1024

data:
  _target_: data.mnist.MNIST
  train: False
  discrete: True
  num_samples: 1000

evaluator:
  _target_: eval.MNIST_evaluator

visualizer:
  _target_: visualize.MNIST_visualizer

exp_dir: exps/mnist_xor
# exp_dir: runtime_ablation